import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import packageJson from "../package.json";

function isSessionStorageAvailable() {
  if (typeof window === "undefined") {
    return undefined;
  }

  try {
      const storage = window["sessionStorage"];
      const x = "__storage_test__";
      storage.setItem(x, x);
      storage.removeItem(x);
      return true;
  }
  catch (e) {
      return false;
  }
}

function isLocalStorageAvailable() {
  if (typeof window === "undefined") {
    return undefined;
  }

  try {
      const storage = window["localStorage"];
      const x = "__storage_test__";
      storage.setItem(x, x);
      storage.removeItem(x);
      return true;
  }
  catch (e) {
      return false;
  }
}

const Home: NextPage = () => {
  const [message, setMessage] = useState("useEffect() is not working.");
  const [localStorageMsg, setLocalStorageMsg] = useState<boolean | undefined>(undefined);

  useEffect(() => {
    setMessage("useEffect() works!");
    setLocalStorageMsg(isLocalStorageAvailable());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next@11 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{background: "black", color: "white"}}>
        <h1 className={styles.title}>
          {message}
        </h1>
        <p>localStorage available: {`${localStorageMsg}`}</p>
      </main>

      <footer className={styles.footer} style={{background: "black", color: "white"}}>
        Version v2.1, nextjs version: {packageJson.dependencies.next}
      </footer>
    </div>
  )
}

export default Home
