import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const keyboardEventToString = (ev: KeyboardEvent): string => {
  return `code: ${ev.code}, key: ${ev.key}, location: ${ev.location}, metaKey: ${ev.metaKey}`;
}

const focusEventToString = (ev: FocusEvent): string => {
  return `target: ${ev.target}`;
}

function setupListeners() {

  window.addEventListener("keydown", (ev) => {
    window.document.getElementById("keyDownStr")!.innerText = `KeyDown: ${keyboardEventToString(ev)}`;
    ev.preventDefault();
  }, false);
  window.addEventListener("keypress", (ev) => {
    window.document.getElementById("keyPressStr")!.innerText = `KeyPress: ${keyboardEventToString(ev)}`;
  });
  window.addEventListener("keyup", (ev) => {
    window.document.getElementById("keyUpStr")!.innerText = `KeyUp: ${keyboardEventToString(ev)}`;
  });
  window.addEventListener("focusin", (ev) => {
    window.document.getElementById("focusStr")!.innerText = `Focus: ${focusEventToString(ev)}`;
    const target = ev.target as any;
    if (target?.style?.background !== undefined) {
      target.style.background = "pink";
    }
  });
  window.addEventListener("focusout", (ev) => {
    const target = ev.target as any;
    if (target?.style?.background !== undefined) {
      target.style.background = "";
    }
  });
}

export default function Home() {

  useEffect(() => {
    window.document.getElementById("messages")!.innerText = "USE EFFECT WORKS!";
    setupListeners();
  });

  return (
    <>
      <Head>
        <title>TV Samples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ background: "yellow" }}>
          <p id="messages">MESSAGES:</p>
          <p id="keyDownStr">KeyDown:</p>
          <p id="keyUpStr">KeyUp:</p>
          <p id="keyPressStr">KeyPress:</p>
          <p id="focusStr">Focus:</p>
        </div>
        <div style={{ display: "flex", gap: 24 }}>
          <button>Button1</button>
          <button>Button2</button>
          <button>Button3</button>
        </div>
      </main>
    </>
  )
}
